language: android

jdk: oraclejdk8

sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-22
  - android-28
  - sys-img-armeabi-v7a-android-22

  #Extras
  - extra-android-m2repository
  - extra-google-m2repository  # Removed duplicated component

before_install:
  - echo yes | android update sdk --all --filter build-tools-28.0.3 --no-ui --force
  - yes | sdkmanager "platforms;android-28"

before_script:    
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - chmod +x ./gradlew
  - ./gradlew jacocoTestReport
  - ./gradlew test
  - ./gradlew connectedAndroidTest
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
